<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>7.3</LangVersion>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <InvariantGlobalization>true</InvariantGlobalization>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RootNamespace>DCFApixels.DragonECS</RootNamespace>

        <Title>DragonECS</Title>
        <Version>1.1.13</Version>
        <Authors>DCFApixels</Authors>
        <Description>Entity Component System framework for C# game engines and .NET</Description>
        <Copyright>Copyright © DCFApixels</Copyright>
        <RepositoryUrl>https://github.com/DCFApixels/DragonECS</RepositoryUrl>
        <PackageProjectUrl>https://github.com/DCFApixels/DragonECS</PackageProjectUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
        <RepositoryType>git</RepositoryType>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageTags>ecs; gamedev; unity; dragonecs</PackageTags>
    </PropertyGroup>

    <ItemGroup>
      <None Include="README.md" Pack="true" PackagePath="" />
      <None Include="LICENSE.md" Pack="true" PackagePath="" />
      <None Remove="**/*.meta" />
      <None Remove="package.json" />
      <None Remove="DragonECS.asmdef" />
    </ItemGroup>
    
</Project>
